### ISSUE TITLE
missing polygonscan/configs/stable.json

### ISSUE THREAD

**Issue by r4VP4** [tarsil/polygonscan-python#1]
polygonscan/configs/stable.json is missing when installing via pip install git+https://github.com/tarsil/polygonscan-python or via pip install polygonscan-python

**Comment by tarsil** [comment]
Thank you very much. I didn't find the using pypy but if you did... Typos on my side. I've merged your suggestion, let me know if you still have those issues.

**Comment by r4VP4** [comment]
Hy, thank you. 
I did a short test:
- The package from PyPI is still is missing the file.
- Installing directly from github with pip install git+https://github.com/tarsil/polygonscan-python wotks perfect.

**Comment by tarsil** [comment]
I installed the package and I can actually see it inside.
