### ISSUE TITLE
Update Usage-section

### ISSUE THREAD

**Issue by remmius** [tarsil/polygonscan-python#3]
Hi, 
Thank you for your work! A really nice lib.
One minor request regarding the documentation. Could you update the Usage section with an actual working example like: for example: 
`from polygonscan import PolygonScan

with PolygonScan("API_KEY",False) as matic:
    print(matic.get_matic_balance(address="0xddbd2b932c763ba5b1b7ae3b362eac3e8d40121a"))`

The current 'example' gives an error as the matic object only has a function "from_session".
The update might save some people some digging.

**Comment by tarsil** [comment]
Nice catch! Updated now with your example :)
