### ISSUE TITLE
How do we monitor sold events?

### ISSUE THREAD

**Issue by jack5parr0w** [tarsil/polygonscan-python#4]
I'm trying to create a Twitter bot to tweet when there is a sale happened for a particular contract. I checked the API https://mumbai.polygonscan.com/apis#accounts but it has very minimal info. https://twitter.com/PenguinNFTSales this is a sample bot I'm trying to replicate how can I do that?

**Comment by tarsil** [comment]
Apologies for taking so long to reply but I have never received a notification from GitHub saying this was here. 

So what you need is a "live event watcher". I not 100% sure that the API can actually do it but have a look at moralis as I believe they have what you want too.
